apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- path: sa-patch.yaml
  target:
    kind: ServiceAccount
    name: kustomize-controller
- path: sops-patch.yaml
  target:
    kind: Kustomization