apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  chart:
    spec:
      # version: "47.x"
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 60m
  install:
    crds: Create
    remediation:
      retries: 9
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 9
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    grafana:
      service:
        type: ClusterIP
      sidecar:
        datasources:
          alertmanager:
            enabled: false
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki-stack:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: true
          jsonData:
            maxLines: 1000
            derivedFields:
              - datasourceUid: tempo
                matcherRegex: "(?:traceID|trace_id)=(\\w+)"
                name: TraceID
                url: '$${__value.raw}'
        - name: Tempo
          type: tempo
          uid: tempo
          access: browser
          orgId: 1
          url: http://tempo-query-frontend:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: true
          jsonData:
            tracesToLogs:
                datasourceUid: Loki
                tags:
                    - job
                    - instance
                    - pod
                    - namespace
            serviceMap:
                datasourceUid: prometheus
            lokiSearch:
                datasourceUid: Loki
      # adminUser: admin
      # adminPassword: admin
      # admin:
      #  ## Name of the secret. Can be templated.
      #   existingSecret: ""
      #   userKey: admin-user
      #   passwordKey: admin-password
      # env:
      grafana.ini:
        # auth:
        #   disable_login_form: true
        # auth.basic:
        #   enabled: false
        auth.anonymous:
          enabled: true
          org_role: Admin
          # org_name: "Admin"
        feature_toggles:
          enable: traceToLogs tempoServiceGraph tempoSearch tempoBackendSearch tempoApmTable traceqlEditor
    alertmanager:
      enabled: false
    prometheus:
      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorNamespaceSelector: {}
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
        enableRemoteWriteReceiver: true
        enableFeatures:
          - exemplar-storage
        additionalScrapeConfigs:
          - job_name: otel_collector
            scrape_interval: 5s
            static_configs:
              - targets: ['otel-collector-opentelemetry-collector:8889']
  postRenderers:
    - kustomize:
        patches:
          - target:
              # Ignore these objects from Flux diff as they are mutated from chart hooks
              kind: (ValidatingWebhookConfiguration|MutatingWebhookConfiguration)
              name: kube-prometheus-stack-admission
            patch: |
              - op: add
                path: /metadata/annotations/helm.toolkit.fluxcd.io~1driftDetection
                value: disabled
          - target:
              # Ignore these objects from Flux diff as they are mutated at apply time but not at dry-run time
              kind: PrometheusRule
            patch: |
              - op: add
                path: /metadata/annotations/helm.toolkit.fluxcd.io~1driftDetection
                value: disabled
