apiVersion: v1
kind: Namespace
metadata:
  name: tns
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: app
  name: app
  namespace: tns
spec:
  ports:
  - name: app-http-metrics
    port: 80
    targetPort: 80
  selector:
    name: app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: db
  name: db
  namespace: tns
spec:
  ports:
  - name: db-http-metrics
    port: 80
    targetPort: 80
  selector:
    name: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: tns
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - args:
        - -log.level=debug
        - http://db
        env:
        - name: JAEGER_AGENT_HOST
          value: otel-collector-opentelemetry-collector.monitoring.svc.cluster.local
        - name: JAEGER_TAGS
          value: cluster=cloud,namespace=tns
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_TRACEID_128BIT
          value: "true"
        image: grafana/tns-app:latest
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 80
          name: http-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: tns
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
      - args:
        - -log.level=debug
        env:
        - name: JAEGER_AGENT_HOST
          value: otel-collector-opentelemetry-collector.monitoring.svc.cluster.local
        - name: JAEGER_TAGS
          value: cluster=cloud,namespace=tns
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_TRACEID_128BIT
          value: "true"
        image: grafana/tns-db:latest
        imagePullPolicy: IfNotPresent
        name: db
        ports:
        - containerPort: 80
          name: http-metrics
