---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kbot
  namespace: demo
spec:
  chart:
    spec:
      chart: ./helm
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: kbot
  interval: 1m0s
  valuesFrom:
  - kind: Secret 
    name: kbot-secret
    valuesKey: token
    targetPath: secret.tokenValue
  values:
    env:
      metrics_host: "otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
      traces_host: "otel-collector-opentelemetry-collector.monitoring.svc.cluster.local"
      app_url: "http://app.tns.svc.cluster.local"
