apiVersion: v1
kind: Secret
metadata:
  name: kbot-secret
  namespace: demo
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: kbot
    meta.helm.sh/release-namespace: demo
data:
  token: NzE3MDAyNDAzNjpBQUdpaUc5OGhmZTVmeFU2d2VwQTdvQjdsX0Fxa1l3REdIdw==
 