apiVersion: v1
kind: Secret
metadata:
    name: kbot-secret
    namespace: demo
    creationTimestamp: null
    labels:
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-name: kbot
        meta.helm.sh/release-namespace: demo
data:
    token: ENC[AES256_GCM,data:xiJTv4GeaWV33aSpR4me9z0t+evQrV6IYfiZetUjzIfACZ7wvVWjAO15/s7dSHDWxrPCfoBh+Xx/6KiepqCPzw==,iv:10fNNUbpkHkYrU2NIjAjTGs9lc/Ksd3vKpKp0HtYMJ0=,tag:qq3+rVdxZ7Sxw1PpLWsoMw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/k8s-k3s-id/locations/global/keyRings/kbot2/cryptoKeys/TELE_TOKEN
          created_at: "2024-05-23T12:29:00Z"
          enc: CiQAGVoUvgzJ1wrGenBuvhlA28gbpdQmqV/Z3Mtp4Sck74VdgZcSSQA0QISVtpsZhk6cDYvg3bsgSJhM4iKcldbOiD6Bhfy6NhJAj9hEmTSpG+WulY2QhWljygG1izw+ommrWpJPqcwZdA67ejSIbTE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-23T12:29:00Z"
    mac: ENC[AES256_GCM,data:sKBhncKBGtiUe9c+ff5J0XwUSHl2V0HgKAzRo0uTsThXvTufk5UZeOi1O6oNNkxzSGG8jLH74y0v84JjPuVz5WuoFrL7RvIUjkWlYKAZb2u0ILC5/G2qycPH0daR9pYCAH7TiJus+YBbPyS3akA3DHRdiUmfXpvOtYkNc1aZJL8=,iv:NPWF6LorlAucVOWeBMAN2S0x/iGXVsyI8NNgZg4XTCY=,tag:jvPtmNWgOA2WFFDFKygXbQ==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.8.1
