apiVersion: v1
kind: Secret
metadata:
    name: kbot-secret
    namespace: demo
    creationTimestamp: null
    labels:
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-name: kbot
        meta.helm.sh/release-namespace: demo
data:
    token: ENC[AES256_GCM,data:A72MxdLDPdSjAzvIIBCjcWJG1+u79XEtvcWsyjBmYs1LoSObQOlW1m52yWuf9GNhFejITYQkFh+p8zPaV4+Z5g==,iv:b5zYLNZEMObnHMFo84tX5B7JlgJ+9BE+HyvG/xm70dQ=,tag:6WJ9ml6jXEhRnFDJhYlfow==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/k8s-k3s-id/locations/global/keyRings/kbot2/cryptoKeys/TELE_TOKEN
          created_at: "2024-05-23T16:02:52Z"
          enc: CiQAGVoUvv+24OqRcB+9sndYsGaDkE8yWNdiFMdqZqcHIT+pwdESSQA0QISVGCXA0pUlC2GzlZ12cwnFIpEefYActGLpISvv8N2LVWkl1ApN6VNB8OvNPp6cOZk8yDb9ctSk2zN3hULnQsKXZ4lvZNc=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-23T16:02:53Z"
    mac: ENC[AES256_GCM,data:w6hoTlApGZrDV/Su2rX6rGWOJcuUc03noqsyrVRCmqPrFYawNGoft/aJFevkZTvruPfnbQhcewe8hJalDBJxDqaYZVcppvFMZlZmLP9bri2IiOsAYKPf3BdIbrfTxRzv9nY65dFpLTeK2LwN00rXP7GxGZabGXjWdsHfG+MdO70=,iv:v4+pfFwhRw/fqWtYnUGyEZi11fi9u+qGTeY9H3PPFWw=,tag:jytOaJsr3snS1HiLP6SNOQ==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.8.1
