apiVersion: v1
kind: Secret
metadata:
    name: kbot-secret
    namespace: demo
    creationTimestamp: null
    labels:
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-name: kbot
        meta.helm.sh/release-namespace: demo
data:
    token: ENC[AES256_GCM,data:MV1jfSWLBsIj/B8zZyTQQTrW+S2YlBlPC8IMwyJ+qVDfqWSyb7UQDAOn3HvXwufVHR5tS1vpOHOinCDypqwZoQ==,iv:znmhylqtzZL4BH8lkx2sg1dtfRpfNyQrsvYUT88vTQk=,tag:ho3WXfmTE4T2WrCHvqiwCA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/k8s-k3s-id/locations/global/keyRings/kbot2/cryptoKeys/TELE_TOKEN
          created_at: "2024-05-23T12:05:28Z"
          enc: CiQAGVoUvrsT4U29Jvo/ONiDTh4f3bgG0S3ppzYDBgQx8Ahyq4QSSQA0QISVJxeV850ynxxcMY4owLgLDb412nKz0RtRx3z3ITT67SZoRe3N7pxBBWfMQZqISHMJ/edovAexqJ0WoCKurmUw/Ovix0I=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-23T12:05:28Z"
    mac: ENC[AES256_GCM,data:gkkDLGA/SaO0EnnoL52vV0fN04pdJgOf/81h8nrJzbLS4K5z1/pDzpYHeBhgDBLcantDzRHdyAXjLyceNIMCtpVNw0ziRnWlCOPJfwq/6TPtzsZMVCDvMtQUcVonlL7o12XW+ld7tF+sD6ueh1TrrIvF4srqgDOQ39zVNUsifhc=,iv:A3XiWu6ygUOtxkmlWTzTNRweMemfWu8kCjGUxterLak=,tag:zxNFOJJ29JsLYmboQHeDKw==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.8.1
