apiVersion: v1
kind: Secret
metadata:
    name: kbot-secret
    namespace: demo
    creationTimestamp: null
    labels:
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-name: kbot
        meta.helm.sh/release-namespace: demo
data:
    token: ENC[AES256_GCM,data:LJPlMsG/tJQGdY1tvo4n0v86vevuEPnhNKHFgamWzGZuyablZepXgfCHfnQq9S6jr63b5M9gFp4Mt2eCPRQGiA==,iv:JZnG5AoZJUXDZLfSkYgu/kmEGUPPQAsAY+Yp4nBXC6s=,tag:KOq8jOMLwApIlXzTvKqq7g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/k8s-k3s-id/locations/global/keyRings/kbot2/cryptoKeys/TELE_TOKEN
          created_at: "2024-05-23T11:58:02Z"
          enc: CiQAGVoUvtX3YuUjnumyiGFBnjinod5usK6ho+vRqHBa4HWvhYwSSQA0QISVSeGVYLx8ThJmYy9KPUadHjaQT2qTEvgkKTMWZwtxYm0MjhlNpwyoJb+UDN/Rw95lcNXuhDXBTrhym7MEuIzjHQYpWr0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-23T11:58:03Z"
    mac: ENC[AES256_GCM,data:zE2OUp8C9sfrhQGA+BKmwv6dYO48kKrLXDemP6i9/Ch4zcuMmvSBuGA4+Dwwc8qJhHeTVsGVA2WBt9d93wLgTXqKtyMa9ZInB4RFdssdRrspsjhbMSZmpHHfBDFMyBu3WPsbjlBSccn5aZZU1Bd6lajPV6QYlR+Xj3LI8KOvQ88=,iv:YYBTMu8nHYM6zZao5wiKC1UsZDz4c2/9kQRNA29+SbI=,tag:BYsEF4Oyuts8lRvi4nlJCQ==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.8.1
