apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 60m
  install:
    remediation:
      retries: 9
  upgrade:
    remediation:
      retries: 9
  values:
    installCRDs: true
